-- =============================================================================
-- 014 — PAYMENT SUBMISSION IDEMPOTENCY (2026-09-07)
-- =============================================================================
-- Additive only. No DROP, no TRUNCATE, no DELETE, no UPDATE of any existing
-- row, no change to any historical migration, no change to any cutover flag,
-- no change to any existing column's type or nullability. Every statement is
-- idempotent (ADD COLUMN IF NOT EXISTS / CREATE UNIQUE INDEX IF NOT EXISTS) so
-- Render's `npm run migrate && npm start` can run it safely, and re-run it
-- safely. Nothing existing is touched, so no backup step is required.
--
-- WHY THIS MIGRATION IS REQUIRED
--
-- POST /api/relational/payments had no idempotency of any kind. services.ts's
-- recordPayment() unconditionally INSERTs a rel_payments row, so the SAME
-- payment submission arriving twice — a retry after an apparent timeout, a
-- response lost on a flaky connection, a double-click that outruns the React
-- `saving` flag — silently creates TWO payments for one real payment event.
-- That is exactly the confirmed live symptom: a payment that looked like it
-- had not saved was recaptured, and both copies later appeared.
--
-- This cannot be solved by comparing amount+date+method. A customer may
-- legitimately pay R5,000 and another R5,000 on the same day by the same
-- method; those are two real payments and must both be accepted. The ONLY
-- honest way to tell "the same submission arriving twice" apart from "two
-- genuinely separate payments" is for the CLIENT to state which submission
-- this is, and for the database to enforce that a given submission can insert
-- at most one row.
--
-- `client_request_id` is that statement of identity. It is:
--   * generated ONCE per payment submission attempt in the browser (not once
--     per click, not once per render), so every retry of the SAME submission
--     carries the SAME value while a second, genuinely separate payment gets a
--     fresh one;
--   * NULLABLE, and NULL for every historical row and for any client that does
--     not send one — the partial index below only constrains non-NULL values,
--     so no existing payment is affected and no existing behaviour changes;
--   * never used for anything except duplicate-submission detection. It is not
--     a business field, is never displayed, and is never used to match, group
--     or reconcile payments.
--
-- The UNIQUE index is what makes the protection authoritative rather than
-- advisory: it holds at the DATABASE write boundary, so it protects against a
-- duplicate arriving from a retry, from a second browser tab, or from any
-- future client, not just from the one code path that happens to check first.
-- recordPayment() catches its violation and returns the ALREADY-PERSISTED
-- payment, so a retry is answered with the original payment's own id and row
-- version — the caller sees success, and exactly one payment exists.
-- =============================================================================

-- ── 1) SUBMISSION IDENTITY COLUMN ───────────────────────────────────────────
ALTER TABLE rel_payments ADD COLUMN IF NOT EXISTS client_request_id TEXT;

COMMENT ON COLUMN rel_payments.client_request_id IS
  'Idempotency key for ONE payment submission attempt, generated by the client and repeated verbatim on every retry of that same submission. NULL for historical rows and for clients that do not send one. Enforced unique (where not null) by uq_rel_payments_client_request_id so a retried submission can never insert a second payment. Never a business field: not displayed, and never used to match, group or reconcile payments.';

-- ── 2) THE ENFORCEMENT ──────────────────────────────────────────────────────
-- PARTIAL index (WHERE client_request_id IS NOT NULL): historical rows and any
-- future row without a key are entirely unconstrained, so two genuinely
-- separate payments of the same amount, date and method remain perfectly legal
-- — they simply carry different keys (or none).
CREATE UNIQUE INDEX IF NOT EXISTS uq_rel_payments_client_request_id
  ON rel_payments (client_request_id)
  WHERE client_request_id IS NOT NULL;
